### ISSUE TITLE
Any os metrics for hivemq?

### ISSUE THREAD

**Issue by xgy560501** [hivemq/hivemq-prometheus-extension#25]

**Comment by LukasBrand** [comment]
HiveMQ Enterprise offers a variety of OS metrics. You can find a complete list here:
https://docs.hivemq.com/hivemq/4.17/user-guide/monitoring.html#available-metrics

The HiveMQ Community Edition only supports a handful of metrics which do not include OS metrics:
https://github.com/hivemq/hivemq-community-edition/wiki/Monitoring#available-metrics
